apiVersion: "v1"
kind: "Service"
metadata:
  name: "prestashop-service"
  #namespace: "prestashop"
  labels:
    app: "prestashop"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    #targetPort: 8080
  selector:
    app: "prestashop"
  type: "NodePort"